on: [push, pull_request]

env:
  XCODE_PATH: /Applications/Xcode_12.2.app

jobs:
  test:
    if: github.event_name == 'pull_request' || github.ref == 'refs/heads/dmz'
    runs-on: macos-10.15
    strategy:
      fail-fast: false
      matrix:
        test-config:
          - { scheme: SwiftLabTests, destination: platform=macOS }
          - { scheme: SwiftLabUITests, destination: platform=macOS }
    steps:
      - uses: actions/checkout@v2
      - run: sudo xcode-select -s $XCODE_PATH
      - run: xcode-select -p
      - run: set -o pipefail && xcodebuild test -scheme '${{ matrix.test-config.scheme }}' -destination '${{ matrix.test-config.destination }}' | xcpretty

  dmz:
    if: github.event_name == 'push' && github.ref == 'refs/heads/dmz'
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: octokit/request-action@v2.x
        id: merge_dmz_in_master
        with:
          route: POST /repos/${{github.repository}}/merges
          base: master
          head: dmz
        env:
          GITHUB_TOKEN: ${{github.token}}
      - if: steps.merge_dmz_in_master.outputs.status != 201
        run: echo "::error::Merge failed" && exit 1
      - uses: octokit/request-action@v2.x
        with:
          route: POST /repos/${{github.repository}}/check-runs
          name: DMZ merge
          head_sha: ${{fromJSON(steps.merge_dmz_in_master.outputs.data).sha}}
          status: completed
          conclusion: success
        env:
          GITHUB_TOKEN: ${{github.token}}
