on: [push, pull_request]

env:
  XCODE_PATH: /Applications/Xcode_12.2.app

jobs:
  test:
    runs-on: macos-10.15
    strategy:
      fail-fast: false
      matrix:
        test-config:
          - { scheme: SwiftLabTests, destination: platform=macOS }
          - { scheme: SwiftLabUITests, destination: platform=macOS }
    steps:
      - uses: actions/checkout@v2
      - run: sudo xcode-select -s $XCODE_PATH
      - run: xcode-select -p
      - run: set -o pipefail && xcodebuild test -scheme '${{ matrix.test-config.scheme }}' -destination '${{ matrix.test-config.destination }}' | xcpretty

  dmz:
    if: github.event_name == push && github.ref == 'refs/heads/dmz'
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: devmasx/merge-branch@v1.3.1
        with:
          type: now
          from_branch: dmz
          target_branch: master
          github_token: ${{ github.token }}
