on: push

env:
  XCODE_PATH: /Applications/Xcode_12.2.app

jobs:
  test:
    runs-on: macos-10.15
    strategy:
      matrix:
        test-config:
          - { scheme: SwiftLabTests, destination: platform=macOS }
          - { scheme: SwiftLabUITests, destination: platform=macOS }
    steps:
      - uses: actions/checkout@v2
      - run: sudo xcode-select -s $XCODE_PATH
      - run: xcode-select -p
      - run: set -o pipefail && xcodebuild test -scheme '${{ matrix.test-config.scheme }}' -destination '${{ matrix.test-config.destination }}' | xcpretty
