on: push

defaults:
  runs-on: macos-10.15

env:
  XCODE_PATH: /Applications/Xcode_12.2.app

jobs:
  build:
    strategy:
      matrix:
        build-config:
          - { scheme: SwiftLab, destination: 'platform=macOS' }
    steps:
      - uses: actions/checkout@v2
      - run: sudo xcode-select -s $XCODE_PATH
      - run: xcode-select -p
      - run: set -o pipefail && xcodebuild clean build -scheme '${{ matrix.build-config.scheme }}' -destination ${{ matrix.build-config.destination }} | xcpretty
  test:
    strategy:
      matrix:
        test-config:
          - { scheme: SwiftLabTests, destination: 'platform=macOS' }
          - { scheme: SwiftLabUITests, destination: 'platform=macOS' }
    steps:
      - uses: actions/checkout@v2
      - run: sudo xcode-select -s $XCODE_PATH
      - run: xcode-select -p
      - run: set -o pipefail && xcodebuild clean test -scheme '${{ matrix.test-config.scheme }}' -destination ${{ matrix.test-config.destination }} | xcpretty
