on: push

jobs:
  build:
    strategy:
      matrix:
        os: [macos-10.15, macos-11.0]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - run: ls -l /Applications
      - run: sudo xcode-select -s /Applications/Xcode_12.2.app
      - run: set -o pipefail && xcodebuild test -scheme SwiftLabTests | xcpretty
      - run: set -o pipefail && xcodebuild test -scheme SwiftLabUITests | xcpretty
